<?php

// This file was generated by running "composer dump-env dev"

return array (
  'APP_ENV' => 'dev',
  'APP_NAME' => 'marieteam',
  'APP_SECRET' => '42b2e5e43b1cdd0b314b60c6a0833d88',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'DATABASE_URL' => 'mysql://c2077914c_marieteam:Test62620@91.234.194.231/c2077914c_marieteam',
  'LOCK_DSN' => 'flock',
);
